# Override for development
version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev