// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azkeakdwogyoajsmdhdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6a2Vha2R3b2d5b2Fqc21kaGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTYwMzYsImV4cCI6MjA3Mzc5MjAzNn0.1Q_nKoNVOCsEu7s1J6Aoa6ADd4Edii7THHS_0Pxkdm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});